# Generated by Django 2.2.5 on 2021-09-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_art',
            field=models.CharField(default='static/album_art/default.png', max_length=100),
        ),
    ]
