# Generated by Django 2.2.5 on 2021-09-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/default_avatar.png', upload_to='avatar'),
        ),
    ]
