# Generated by Django 2.2.5 on 2021-09-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210920_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='static/default_avatar.png', upload_to='avatar'),
        ),
    ]
