# Generated by Django 2.2.5 on 2021-10-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20211002_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='avatar/default_avatar.png', upload_to='avatar'),
        ),
    ]
